name: Docker Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 20.4.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.4.x'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Healthcheck Docker versions
      run: |
        node -v
        docker -v
        docker-compose -v

    - name: Start dev
      run: node .github/scripts/start.js

    - name: Run tests
      run: ./test
