name: Docker Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Healthcheck Docker versions
      run: |
        echo $(docker -v)
        echo $(docker-compose -v)

    - name: Start dev
      if: false
      run: |
        ./dev &

    - name: Docker Compose down
      if: false
      run: |
        ./test
